### ISSUE TITLE
npm install fails at electron-rebuild

### ISSUE THREAD

**Issue by wolframroesler** [railsware/upterm#1065]
Trying to install on Linux Mint. TLDR:

```
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild
```

Here's the output of "npm install". Installed node and npm with apt install just today. Here's the install log file (renamed to .log.txt because github doesn't like .log): [npm-debug.log.txt](https://github.com/railsware/upterm/files/1036130/npm-debug.log.txt)

Thanks!

```
$ npm install

> electron-chromedriver@1.7.1 install /home/wolfram/upterm/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> upterm@0.2.153 preinstall /home/wolfram/upterm
> npm prune


> upterm@0.2.153 postinstall /home/wolfram/upterm
> electron-rebuild

/home/wolfram/upterm/node_modules/electron-rebuild/lib/src/rebuild.js:33
    constructor(lifecycle, buildPath, electronVersion, arch = process.arch, extraModules = [], forceRebuild = false, headerURL = 'https://atom.io/download/electron', types = ['prod', 'optional'], mode = defaultMode) {
                                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wolfram/upterm/node_modules/electron-rebuild/lib/src/cli.js:16:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-mac:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-mac@1.0.1
npm WARN ajv-keywords@2.0.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! upterm@0.2.153 postinstall: `electron-rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.2.153 postinstall script 'electron-rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wolfram/upterm/npm-debug.log
```

**Comment by vlad-shatskyi** [comment]
Please update your node.js to the latest version.
