### ISSUE TITLE
Can't understand how make and run this application on linux

### ISSUE THREAD

**Issue by itJunky** [railsware/upterm#1320]
First of all, i need a normal instruction with steps and all dependencies what i need to install and execute at installation process. 

It's broke when i try install and run it nativlly on my ubuntu 18
alp ▶ jeffxt ▶ ~ ▶ src ❯ upterm-0.4.4 ▶ $ ▶ npm run pack
npm WARN npm npm does not support Node.js v10.13.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> upterm@0.4.4 pack /home/alp/src/upterm-0.4.4
> build

  • electron-builder version=20.10.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=1.8.6 appOutDir=dist/linux-unpacked
Downloading tmp-21277-1-SHASUMS256.txt-1.8.6
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)
Error: Application entry file "compiled/src/main/Main.js" in the "/home/alp/src/upterm-0.4.4/dist/linux-unpacked/resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at /home/alp/src/upterm-0.4.4/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at checkFileInArchive (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/asar/asarFileChecker.js:78:17)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/platformPackager.ts:355:13
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.checkFileInPackage (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/platformPackager.js:563:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/platformPackager.ts:404:16
    at Generator.next (<anonymous>)
    at /home/alp/src/upterm-0.4.4/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at LinuxPackager.sanityCheckPackage (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/platformPackager.js:585:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/platformPackager.ts:231:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at LinuxPackager.doPack (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/platformPackager.js:400:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/platformPackager.ts:116:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/platformPackager.js:265:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/alp/src/upterm-0.4.4/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/alp/src/upterm-0.4.4/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/packager.js:605:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /home/alp/src/upterm-0.4.4/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/alp/src/upterm-0.4.4/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/packager.js:532:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/packager.ts:289:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/packager.js:491:7)
    at /home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/alp/src/upterm-0.4.4/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/home/alp/src/upterm-0.4.4/node_modules/electron-builder/src/builder.ts:229:10)
    at then (/home/alp/src/upterm-0.4.4/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (/home/alp/src/upterm-0.4.4/node_modules/electron-builder/src/cli/cli.ts:43:10)
    at Object.runCommand (/home/alp/src/upterm-0.4.4/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/alp/src/upterm-0.4.4/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/alp/src/upterm-0.4.4/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/alp/src/upterm-0.4.4/node_modules/electron-builder/src/cli/cli.ts:28:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! upterm@0.4.4 pack: `build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upterm@0.4.4 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alp/.npm/_logs/2019-02-10T09_37_50_318Z-debug.log
```


When i run `docker build .` it's broke too:
```
alp ▶ jeffxt ▶ ~ ▶ src ❯ upterm-0.4.4 ▶ $ ▶ ls -l dist/linux-unpacked/upterm 
-rwxr-xr-x 1 alp alp 73912232 апр 26  2018 dist/linux-unpacked/upterm
 alp ▶ jeffxt ▶ ~ ▶ src ❯ upterm-0.4.4 ▶ $ ▶  dist/linux-unpacked/upterm 
Gtk-Message: 12:46:36.592: Failed to load module "overlay-scrollbar"
Gtk-Message: 12:46:36.593: Failed to load module "unity-gtk-module"
Gtk-Message: 12:46:36.593: Failed to load module "atk-bridge"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/alp/src/upterm-0.4.4/dist/linux-unpacked/resources/app.asar/compiled/src/main/Main.js'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/alp/src/upterm-0.4.4/dist/linux-unpacked/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Object.<anonymous> (/home/alp/src/upterm-0.4.4/dist/linux-unpacked/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/home/alp/src/upterm-0.4.4/dist/linux-unpacked/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by richardaum** [comment]
I'm using Linux Ubuntu 18. After running `npm start` the application opens. Then I run `npm run pack` and it works. Probably because `npm start` runs `npm compile` which seems to be the right way here.

**Comment by codejanovic** [comment]
@itJunky 
i am at version 18.10 and the following worked for me:

- install latest nodejs (v10.15.1) / npm (v10.15.1)
` curl -sL https://deb.nodesource.com/setup_10.x | sudo bash - `
`sudo apt install nodejs`
- checkout upterm master
`git@github.com:railsware/upterm.git`
- build and run upterm
`sudo npm start`
- install additional packages if npm fails. libgconf failed for me:
`sudo apt -y install libgconf2-4`
- rebuild and rerun upterm if needed
`sudo npm start`
- build the app artifact if you want to install it to your system with
`npm run pack`
- install the generated artifact that lies in upterms `/dist` folder
`./upterm-0.4.4-x86_64.AppImage`

**Comment by Billy-** [comment]
I also can't run this at all. `npm start` gives me loads of errors from the `tsc` script. Tried with both node 8 and 10. Running docker build gives me the same errors @itJunky had. Trying to run the `.AppImage` from the releases page opens up VLC player. :frowning_face:
